### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by xeoshow** [julmot/datatables.mark.js#7]
npm error saying markjs module not found

### Steps to reproduce

Just run : 
require('mark.js') 
require('datatables.mark.js')  

### Environment

- Browser name and version
- jQuery version 2.2.0
- DataTables version - DataTables 1.10.13
- mark.js v8.8.3
- datatables.mark.js v2.0.0

**Comment by xeoshow** [comment]
Just modified to below then works well (changed markjs to mark.js)

> 

    if (typeof define === "function" && define.amd) {
        define(["jquery", "datatables.net", "mark.js"], function (jQuery) {
            return factory(window, document, jQuery);
        });
    } else if ((typeof exports === "undefined" ? "undefined" : _typeof(exports)) === "object") {
        require("datatables.net");
        require("mark.js");

**Comment by xeoshow** [comment]
But seems after the change, will get below problem, how to resolve? Thanks!

> (unknown)

 Error: jquery.mark.js is necessary for datatables.mark.js

**Comment by julmot** [comment]
@xeoshow Thanks for submitting. What module loader are you using (e.g. Webpack)?

**Comment by xeoshow** [comment]
ye s I used webpack

**Comment by julmot** [comment]
As far as I can see we can only add the dot in `markjs` in case of Node-like environments (Webpack). The `define` block still needs  `markjs` as RequireJS otherwiese tries to load a file `mark.js` instead of the module (which may be located in a different place).

I'd classify this as bug.

`Error: jquery.mark.js is necessary for datatables.mark.js`: This happens as datatables.mark.js needs the file `jquery.mark.js` not `mark.js` (the jQuery version).

**Comment by xeoshow** [comment]
Could you please kindly tell if the bug has been fixed? If I use npm install, does it works out of the box now? Thanks!

**Comment by julmot** [comment]
@xeoshow Sorry for my late answer. I'd like to help you with a fix asap, but I'm confused because I see some issues and need some help. First of all, lets clarify the names that are beeing loaded:

1. The `define` in `datatables.mark.js` is necessary for AMD loaders like RequireJS. And since RequireJS tries to load a `mark.js` file in the same directory if you define a module that needs `mark.js` I've chosen the name `markjs` which then loads the module mark.js defined in a RequireJS config.
2. The `define` in `datatables.mark.js` also loads `datatables.net`. The datatables `.net` suffix was introduced in [v2.0.0](https://github.com/julmot/datatables.mark.js/releases/tag/v2.0.0) since datatables specified that. But, it seems that in Node.js environments it isn't `datatables.net`, instead it seems to be `datatables`. @DataTables Can you please help clarify the reason?

So, this is the reason why these module names are loaded. However, I'm confused why Webpack uses the [`define` (AMD) way](https://github.com/julmot/datatables.mark.js/blob/v2.0.0/dist/datatables.mark.js#L18), and not the [CommonJS](https://github.com/julmot/datatables.mark.js/blob/v2.0.0/dist/datatables.mark.js#L21). @xeoshow Do you know the reason?

Since we can't change the name as this would make it incompatible with AMD loaders, I'd recommend to make:

- the loaded module "markjs" (loaded in datatables.mark.js) available under the name "mark.js" too
- the loaded module "datatables.net" (loaded in datatables.mark.js) available under the name "datatables" too

To do this, you'd need to specify alias names in your `webpack.conf.js` configuration:

```javascript
module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    resolve: {
        alias: {
            "datatables.net": "datatables/media/js/jquery.dataTables.js",
            "markjs": "mark.js/dist/jquery.mark.js"
        }
    }
};
```

The problem that still exists with this solution is that if you run `require("datatables.mark.js");` the files are beeing packad in the wrong order:

![2017-03-11_141854](https://cloud.githubusercontent.com/assets/8310677/23823582/acb8abf4-0665-11e7-8b51-66fc753d42eb.png)

@xeoshow Do you know a way to resolve this?

Last but not least, the `require("markjs");` inside `datatables.mark.js` loads the `dist/mark.js` file that is specified in mark.js `package.json`. But, this is not the file `datatables.mark.js` needs, as you already know. It needs `dist/jquery.mark.js`. You could specify an alias name that points to `node_modules/mark.js/dist/jquery.mark.js`. However, `datatables.mark.js` doesn't know how you name that alias, so it wouldn't be possible to `require` it. Furthermore, as mentioned, Webpack uses the AMD path (see above) and not the CommonJS path, so we couldn't change the names anyway. I'm not sure how this should be solved.

Beside of that, I've noticed that if you install `datatables.mark.js` via `$ npm install julmot/datatables.mark.js` the necessary dependencies (jQuery, mark.js) aren't beeing installed. I'll add them to `package.json` to fix this.

- [ ] Add jQuery and datatables to package.json as "dependency"

I'd appreciate any help for above named confusions I have.

**Comment by julmot** [comment]
@xeoshow This should finally be solved in [v2.0.1](https://github.com/julmot/datatables.mark.js/releases/tag/v2.0.1).

**Comment by MaxKostenko** [comment]
I tried pack like this
import "mark.js";
import "datatables.mark.js";
And problem still exists. Aliases in configuration solved it.

**Comment by julmot** [comment]
@MaxKostenko Thanks for reporting. Can you please share some additional config?

**Comment by MaxKostenko** [comment]
Webpack config
`const Encore = require("@symfony/webpack-encore");
const AssetsPlugin = require("assets-webpack-plugin");
const Webpack = require("webpack");

Encore
// directory where all compiled assets will be stored
    .setOutputPath("web/wp2b/")

    // what"s the public path to this directory (relative to your project"s document root dir)
    .setPublicPath("/wp2b")

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // allow legacy applications to use $/jQuery as a global variable
    //.autoProvidejQuery()

    .addPlugin(new AssetsPlugin({prettyPrint: true}))
    /*
        .addLoader({
            test: require.resolve("jquery"),
            loader: "expose-loader?$!expose-loader?jQuery"
        })*/
    .addPlugin(new Webpack.ProvidePlugin({
        "$": "jquery",
        "jQuery": "jquery",
        "document.jQuery": "jquery",
        "window.jQuery": "jquery"
    }))
    .addEntry("some-entry", "./assets/some-entry")


    // allow sass/scss files to be processed
    .enableSassLoader()


    .enableSourceMaps(!Encore.isProduction())

    // create hashed filenames (e.g. app.abc123.css)
    .enableVersioning()
;

const config = Encore.getWebpackConfig();

config.resolve = {
    alias: {
        "jquery-ui": "components-jqueryui",
        "datatables.net": "datatables/media/js/jquery.dataTables.js",
        "markjs": "mark.js/dist/jquery.mark.js"
    }
};
`

Entry imports:
`
import "datatables.net";
import "datatables.net-zf";
import "mark.js";
import "datatables.mark.js";
......
`

**Comment by julmot** [comment]
@MaxKostenko Please adjust your imports to:

```js
import "datatables.mark.js";
import "datatables.net-zf";
```

and try again. Information about this:

- datatables.mark.js depends on datatables.net already and will load it
- it also depends on mark.js, but not the default file, rather the jQuery version, so
- With the import of datatables.mark.js you're also importing jQuery, datatables.net and the correct mark.js file so no further imports should be necessary

See https://github.com/julmot/datatables.mark.js/blob/v2.0.1/build/templates/datatables.mark.js#L13

**Comment by MaxKostenko** [comment]
Your way of import still works only with:
```
    alias: {
        "markjs": "mark.js/dist/jquery.mark.js"
    }
```
I tried uninstall packages and install only "datatables.mark.js", "datatables.net-zf". It didn't help.

> This dependency was not found:
> * markjs in ./node_modules/datatables.mark.js/dist/datatables.mark.js

**Comment by julmot** [comment]
@MaxKostenko This is interestingly as it means that in your case, the AMD version of the plugin is used and not the CommonJS version. So it seems that it's not going into `if (typeof exports === 'object') {` which it should. What's your exact environment? Which version of Webpack are you using?

**Comment by Omranic** [comment]
@julmot Thanks for the awesome plugin, but this issue still exists using webpack 3, and it's solved only using the alias names config.

**Comment by sipy** [comment]
Any updates on this? I have the same problem with v2.0.1...

**Comment by sipy** [comment]
For those using laravel-mix, this resolves the issue:

`mix.webpackConfig({
    resolve: {
        alias: {
            "markjs": "mark.js/dist/jquery.mark.js"
        }
    }
});`

**Comment by MohamadElmordaa** [comment]
@sipy  it is not working from my side and i am using symfony, do you have any idea ? thanks
